### ISSUE TITLE
All commands error out on line 687

### ISSUE THREAD

**Issue by gdvine** [somewebmedia/hc-sticky#17]
I'm using followScroll:false on my initial call. Later (on resize), I try calling any of the commands (stop, off,on,destroy,reinit) and hc-sticky errors out with this:

```
TypeError: $(...).data(...) is undefined
$(this).data(pluginName).commands[userOptions].call(this);
```

**Comment by ALTELMA** [comment]
+1

**Comment by somewebmedia** [comment]
Obsolete.
