### ISSUE TITLE
HC-Sticky breaks Chosen (or viceversa)

### ISSUE THREAD

**Issue by alfonsomunozpomer** [somewebmedia/hc-sticky#19]
Hi, I just wanted to let you know that when hc-sticky.js is included in a page where the plug-in [Chosen](https://github.com/harvesthq/chosen) is used, Chosen breaks.

You can see it in the following fiddle: http://jsfiddle.net/q37k614d/

If you remove hc-sticky.js and run it again, you’ll see that the multiple select element renders properly.

**Comment by alfonsomunozpomer** [comment]
The problem seems to be the naming of the style plugin. I renamed it to hcStyle and it works nicely with Chosen. If you want I can send a pull request.

**Comment by somewebmedia** [comment]
Obsolete.
