### ISSUE TITLE
Border issue

### ISSUE THREAD

**Issue by lame07** [somewebmedia/hc-sticky#20]
I am sorry, have a little problem in using github.

On resizing it's going up and down 1-2px; it irritated me and I found the problem.
But here is a little fix:

$resize_clone = $this.clone().attr('style', '').css({
                                visibility: 'hidden',
                                height: 0,
                                overflow: 'hidden',
                                paddingTop: 0,
                                paddingBottom: 0,
                                marginTop: 0,
                                marginBottom: 0
                            });

should be like this

$resize_clone = $this.clone().attr('style', '').css({
                                visibility: 'hidden',
                                height: 0,
                                overflow: 'hidden',
                                paddingTop: 0,
                                paddingBottom: 0,
                                borderTop: 0,
                                borderBottom: 0,
                                marginTop: 0,
                                marginBottom: 0
                            });

**Comment by somewebmedia** [comment]
Obsolete. New major version available.
