### ISSUE TITLE
Fork for Node.js

### ISSUE THREAD

**Issue by alfonsomunozpomer** [somewebmedia/hc-sticky#26]
HC-Sticky is the best sticky plugin I’ve tried (and I’ve tried a few, believe me!) and it’s used in the [Gene Expression Atlas](http://www.ebi.ac.uk/gxa). We modified it to use it with our Node.js stack. Due to the lack of updates for almost a year, I’ve created a fork of HC-Sticky to use with Node.js. It’s in a very early yet functional state. If you want to have a look at it, go to https://github.com/alfonsomunozpomer/hc-sticky. Suggestions and bug fixes are all welcome!

**Comment by somewebmedia** [comment]
Thats great! I'll certainly take a look.

I have a ver2.0 ready for a few months now, but I didn't have time to
publish it yet. It is jQuery free, meaning it is pure JS.

Would you like to test it?

**Comment by alfonsomunozpomer** [comment]
It’d be great! We’d be deligthed to test it. We use React in our front-end, so any visual element that depends on jQuery feels a bit like a kludge.

Thanks a lot for reaching out. It’s also very good news to know that you’re still working on HC-Sticky. I thought you had moved to something else entirely.

**Comment by somewebmedia** [comment]
Can you leave me some email where I can send you the script for testing?

Or just write to somewebmedia@gmail.com

**Comment by codeheroics** [comment]
@somewebmedia Could you please push the version pure JS version you're talking about on a Github branch, even if it's not completely ready yet? I'd love to use hc-sticky in a project, but as I'm using React, modifying the DOM with the plugin isn't ideal.

**Comment by somewebmedia** [comment]
New major version available!
