### ISSUE TITLE
Sticked object taller than viewport rapidly activate/deactivates sticky on scroll at bottom

### ISSUE THREAD

**Issue by fallenturtle** [somewebmedia/hc-sticky#32]
I have a page with an element that is supposed to be sticky when scrolling down. The element is tall and when the viewport is shorter than the element and you scroll down its fine until you scroll to the bottom of the stuck element. At this point if you continue scrolling down the page the stuck element rapidly turns on and off the "sticky-active" and "sticky" selectors causing the element to jump up and down by about 10 or so pixels rapidly. It looks bad and I can't figure out how to make it not do this. Any thoughts?

**Comment by jamesckemp** [comment]
Hey, I'm experiencing this. Did you close because you solved it?

**Comment by jamesckemp** [comment]
Ah, looks like it's caused if the following is true:

1. The sticky element is taller than the `window`
2. The last element inside the sticky has margin-bottom

**Comment by somewebmedia** [comment]
@jamesckemp can you provide me with a demo of this bug?
