### ISSUE TITLE
Absolutely positioned elements within parent containers render incorrectly

### ISSUE THREAD

**Issue by jaichandra** [somewebmedia/hc-sticky#36]
When `hcSticky()` is applied to absolutely positioned elements, the layout breaks.

Refer to below example:
http://jsfiddle.net/kleptomac/ju5esLh8/

The sidebar on the right is pushed out of the window when `hcSticky()` is applied. Commenting out the JS renders the sidebar in the correct position.

Expected behavior:
The default layout should not break when `hcSticky()` is applied to an element.

**Comment by somewebmedia** [comment]
Obsolete. New major version available.
