### ISSUE TITLE
jQuery 3

### ISSUE THREAD

**Issue by redpik** [somewebmedia/hc-sticky#38]
HC-Sticky doesn't work on jQuery 3.

`TypeError: a.indexOf is not a function`

**Comment by Lamecarlate** [comment]
I have the same problem. It's because it uses `.load()`, which is deprecated since 1.8 and removed in 3. Replace `$window.load(function(){` by `$window.on('load', function(){`. (I'll file a pull request)

**Comment by somewebmedia** [comment]
Obsolete. New major version available.
