### ISSUE TITLE
How do disable for mobile and tablet?

### ISSUE THREAD

**Issue by farreal** [somewebmedia/hc-sticky#43]
I am having trouble understanding how I can disable this plugin for mobile and tablet users. at the moment I've tried using the `destroy` and the `onresize` options but I am obviously doing something wrong. Can anyone direct me on how these are supposed to be combined so I can create the state change I need? 

```
$(document).ready(function(){
  $("[data-sticky_column_1]").hcSticky({
    stickTo: "[data-sticky_parent_1]",
    onResize: function () {
      console.log(arguments);
    }
  });

```
Thanks!

**Comment by carasmo** [comment]
I downloaded the [master](https://github.com/somewebmedia/hc-sticky/archive/master.zip) and there are examples for disabling for media queries in the `demo / build` directory

You can't disable for _actual_ device tablets and/or phones with this script, or any other similar script. If you need to do that, I would use server side detection, for example [Mobile Detect php class](https://github.com/serbanghita/Mobile-Detect).

**Comment by farreal** [comment]
@carasmo Thank you - at least that's a start!

Say if I want to disable the script from 768px (typical tablet) downwards how would I manipulate this to cater for that kind of request?

```
      queries: {
        980: {
          disable: true
        }
      }
```

**Comment by carasmo** [comment]
Change the breakpoint to 767. You can see what options in the [read me: ](https://github.com/somewebmedia/hc-sticky):

**Comment by farreal** [comment]
Of course! 🤪 

thank you

**Comment by carasmo** [comment]
Cool. Please close, this is not a bug report or a feature request. Thanks!
