### ISSUE TITLE
Please add Spacer class name

### ISSUE THREAD

**Issue by vovkasolovev** [somewebmedia/hc-sticky#44]
Hi!
I had to use the script in the `<ul>` sidebar on the last `<li>` element. For some reason, the created `div` Spacer does not copy the `list-style-type` attribute value from `<li>` and shown as a default list item with disk. Please add to the Spacer some class name, in order to be able fix directly any such special occasions.

Thank you! Great script!

**Comment by somewebmedia** [comment]
Sorry for the late response. Class name 'sticky-spacer' added in the newest version.
