### ISSUE TITLE
v2.1.3 does not sticks div in IE11

### ISSUE THREAD

**Issue by ballios** [somewebmedia/hc-sticky#45]
I've updated on HC-Sticky 2.1.3.
But in HC-Sticky 2.1.3 the divs (any sticked object) start dont stick in IE11.
There is not such problem in v2.1.1
What happened?

**Comment by 3mcd** [comment]
Looks like it might be related to this line:

https://github.com/somewebmedia/hc-sticky/blob/master/src/hc-sticky.helpers.js#L183

**Comment by Pseudo-Nym** [comment]
I'm having same basic problem. 2.1.3 broken in IE and MS Edge getting error in console "Object doesn't support property or method 'forEach'" tracks back to where 3mcd indicated.

**Comment by somewebmedia** [comment]
Fixed with the newest version (`2.1.4`).
