### ISSUE TITLE
Update() method can't work ????

### ISSUE THREAD

**Issue by KytoSai** [somewebmedia/hc-sticky#48]
I try setimeout to update top value from 10 to 30. But it cannot work ???
Demo: http://noibatdau.com/demo/Fix/demo_1.html

**Comment by KytoSai** [comment]
I try fash your source ...

I see:
http://prntscr.com/j8bhpc

I think it will be useful for you. Thank you !
I love this plugin !

**Comment by somewebmedia** [comment]
Thanks for your input, I appreciate it. I just pushed the latest version, the bug should be fixed now.
