### ISSUE TITLE
Uncaught TypeError: Cannot read property 'queries' of undefined

### ISSUE THREAD

**Issue by Bluxart** [somewebmedia/hc-sticky#57]
Hi, I have included this script in WordPress.
But I have this error: **Uncaught TypeError: Cannot read property 'queries' of undefined**

I used the default jQuery version bundled with WordPress 4.9.8

Image Reference: https://cl.ly/195da84f9347

**Comment by somewebmedia** [comment]
Are you using the latest version of hc-sticky? And can you provide me with the code you are calling the sticky?

**Comment by Bluxart** [comment]
Hi, yes I used the last version 2.2.3

I used the default jQuery example code:

`jQuery(document).ready(function($) {
  $('#element').hcSticky({
    stickTo: '#content'
  });
});`

Or this

`jQuery(document).ready(function($) {
  $('#element').hcSticky();
});`

return me the error...I tested also some old version of plugin but have the same error in console log.

**Comment by Bluxart** [comment]
I have make some test ( change the position about calling script ) and now the error disappear and work the last version.

Thanks.

**Comment by iamplugged** [comment]
@somewebmedia Pls close.

**Comment by sagarponnur** [comment]
jquery.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'isEmptyObject')
    at setOptions (hc-sticky.min.js:102:19)
    at new hcSticky (hc-sticky.min.js:698:5)
    at HTMLDivElement.<anonymous> (hc-sticky.min.js:731:24)

I getting error in console. 
Wordpress theme - Urna
hc-sticky.min.js  is integrated in theme.
hc-sticky.min.js  - 2.2.7

Can you help me with that, please?
