### ISSUE TITLE
Demos suspended

### ISSUE THREAD

**Issue by Crisfole** [somewebmedia/hc-sticky#59]
Looks like a great library! I wanted to see it work, but the demo's host account is suspended....

**Comment by strelok1** [comment]
Demos are in demo/build folder, I just opened index.html locally and they're all there.

**Comment by Almo7aya** [comment]
@somewebmedia Can you host the demos using GitHub pages?

**Comment by somewebmedia** [comment]
Demos moved to gh pages: http://somewebmedia.github.io/hc-sticky/
