### ISSUE TITLE
window resize

### ISSUE THREAD

**Issue by yuhao-nyc** [somewebmedia/hc-sticky#6]
Hi thanks for the awesome plugin, I recently implemented it in my project and it comes out with a little issues.
It seems everytime I resize the browser window. the sticky sidebar will just stick to its old position. I have to manually refresh it, then those sidebar will go back to where is belong.
Same thing with the webpage's responsiveness.
I hope i describe the question in a proper way. 
thanks

**Comment by prashen** [comment]
Hi there,

I am using your plugin and it's really nice. I am getting the same error just above. Can you please tell us how to fix resize styles fixed on sticky target elements. Are you working on this specific issue?

Thanks in advance.

**Comment by luchorengo** [comment]
You could try using reinit method on window resize event. Something like

`$(window).resize(function() {
	    	$('.content').hcSticky('reinit');
    });`

**Comment by somewebmedia** [comment]
Obsolete.
