### ISSUE TITLE
Google Chrome | When bookmarksbar is show (ctrl + shift + b) sticky conteiner a little hide under bar

### ISSUE THREAD

**Issue by banha-serhii** [somewebmedia/hc-sticky#63]
In Google Chrome (other browser do not testing) after using this plugin with jQuery, sticky container hide under bookmarks bar, when scroll down, and display good when scroll up

**Comment by somewebmedia** [comment]
If this is still relevant, a screenshot would be helpful, thanks.

**Comment by banha-serhii** [comment]
Ohhh, I can't even remember what kind of project it is)

**Comment by banha-serhii** [comment]
Thanks, for your reply. At this momnet you cant close this issue
