### ISSUE TITLE
Cannot read property 'queries' of undefined

### ISSUE THREAD

**Issue by loevgaard** [somewebmedia/hc-sticky#67]
I get this error:

![image](https://user-images.githubusercontent.com/2412177/76620748-2d3b8d80-652e-11ea-984c-7d1eb3d5e1e1.png)

Here is my code:

```
const HcSticky = require('hc-sticky');

$(document).ready(() => {
  const stickyHeader = new HcSticky('.header-global'); 
});
```

It works if I do this:

```
const stickyHeader = new HcSticky('.header-global', {});
```

I think it has something to do with this: https://github.com/somewebmedia/hc-sticky/blob/master/src/hc-sticky.js#L88

I am JS newb, so can't help with a PR :(

**Comment by somewebmedia** [comment]
This should be fixed by now in the latest version.

**Comment by loevgaard** [comment]
Thank you!
