### ISSUE TITLE
Radio buttons lose the "checked" property on resize.

### ISSUE THREAD

**Issue by MentalAtom** [somewebmedia/hc-sticky#7]
When you resize the window with a hcSticky containing radio buttons, the checked property is lost (they become un-checked again). Turning the "responsive" option off fixes this, but causes many more issues as the page is responsive.

Thanks

**Comment by nkpgardose** [comment]
:+1:

**Comment by somewebmedia** [comment]
Obsolete.

**Comment by iconicwp** [comment]
This still happened for me. On sticky init my checked radio button lost its "checked" value.

I've got around it for now by resetting it if its not set on "onStart" and "onStop" but it's not ideal.

**Comment by iconicwp** [comment]
-- Please reply above this line --


Hey Somewebmedia/hc-Sticky,

 Thanks for contacting Iconic!

 This is just a quick note to let you know I have received your email,
and will respond as soon as I can.

 My support hours are between 9AM-5PM GMT MONDAY TO FRIDAY, but it may
take up to 48 HOURS for me to get back to you.

 In the meantime, please check the documentation site [1] for answers
to our most frequently asked questions.

 Thanks,
 James

Links:
------
[1] http://docs.iconicwp.com

**Comment by somewebmedia** [comment]
@iconicwp Fixed with the newest version.

**Comment by iconicwp** [comment]
-- Please reply above this line --


Hey Somewebmedia/hc-Sticky,

 Thanks for contacting Iconic!

 This is just a quick note to let you know I have received your email,
and will respond as soon as I can.

 My support hours are between 9AM-5PM GMT MONDAY TO FRIDAY, but it may
take up to 48 HOURS for me to get back to you.

 In the meantime, please check the documentation site [1] for answers
to our most frequently asked questions.

 Thanks,
 James

Links:
------
[1] http://docs.iconicwp.com
