### ISSUE TITLE
Smooth transition on Update Offset?

### ISSUE THREAD

**Issue by steve231293** [somewebmedia/hc-sticky#73]
Hello there,

Could you make smooth transition for sticky elements when update "offset" setting?

**Comment by somewebmedia** [comment]
I'm not sure I follow. Can you give me an exact example of the desired behaviour?

**Comment by steve231293** [comment]
Hello @somewebmedia 

For eg:

When I scroll up then I want to show sticky header, now I need to update offset top.
Everything is ok now. But there is no transition for top.
I know CSS **transition** not working with **top** maybe use CSS **translateY** instead of?

**Comment by somewebmedia** [comment]
Ah, I see. It's not possible with this lib. It's using position absolute and top property, so it would have to be animated, which would add an extra complexity to it which I don't think could be done because the lib is already complex by itself. Sorry.

**Comment by steve231293** [comment]
Oki, thank you for your quick reply.
