### ISSUE TITLE
Problem on Android device

### ISSUE THREAD

**Issue by m1gavin** [somewebmedia/hc-sticky#8]
I'm using Version: 1.2.43 of hc-sticky. It works perfectly on all of the other browsers I've tested it on, however using the android default browser (I'm using phonegap build) the header jumps down ever so slightly if the user scrolls too early. If the user waits 2 seconds or so it doesn't jump and acts as expected. If you have any recommendations to prevent this jump or require and further information please let me know.

**Comment by somewebmedia** [comment]
Obsolete.
