### ISSUE TITLE
Float attribute not cloned in IE8

### ISSUE THREAD

**Issue by timprint** [somewebmedia/hc-sticky#9]
Thanks for the plug-in, it's great.

I have a small issue in IE8. The div I am applying hc-sticky to is "float: left;".
The float attribute is not being added to the inline styles of "wrapper-sticky".
All the other attributes are being added in IE8.
The float attribute is being added in all other browsers I've tested.

Any ideas what could be causing that?

**Comment by somewebmedia** [comment]
Obsolete.
